"""Generate paper/tables/*.tex and paper/numbers.tex from results/ files.

Every number that appears in the manuscript originates here, read directly from
the results files — nothing is hand-typed. Prose references values via
\\rv{key} macros defined in paper/numbers.tex (see paper/rvmacros.tex).

Usage:
  .venv/bin/python scripts/make_tables.py            # regenerate everything
  .venv/bin/python scripts/make_tables.py --check    # verify: no drift, all \\rv keys
                                                     # resolve, no bare literals in prose

Notes on the underlying files (verified 2026-09-01):
- phase1_frontier*.json rows are FA-sorted per arm -> ALWAYS join on the config
  name string in m["config"]; never rely on row order.
- recall_at_k is at each config's own k (3/5/8); never label a column "recall@5".
- phase1_retrieval_summary.json is stale (nulls for bge/pubmedbert); the per-run
  retrieval_report.json files are authoritative.
- accuracy_when_answering is conditional on answering (selection effect);
  coverage-normalized accuracy (correct/400) is recomputed here from completions.
- unparseable_rate's denominator is all 650 rows (both splits).
"""
import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
from config import RESULTS, ROOT, REFUSAL_STRING
from metrics import parse_response

PAPER = ROOT / "paper"
TABLES = PAPER / "tables"

HEADER = ("% GENERATED by scripts/make_tables.py — DO NOT EDIT BY HAND.\n"
          "% Regenerate: .venv/bin/python scripts/make_tables.py\n")

ARMS = {"qwen": "", "terra": "_openai", "llama": "_llama"}
ARM_LABEL = {"qwen": "Qwen2.5-7B", "terra": "GPT-5.6-terra", "llama": "Llama-3.1-8B"}

# Canonical narrative order for tables (file order is FA-sorted and differs per arm).
CONFIG_ORDER = ["p1_base", "p1_bge", "p1_pubmedbert", "p1_bm25", "p1_hybrid",
                "p1_chunk256", "p1_chunk1024", "p1_k3", "p1_k8", "p1_rerank",
                "p1_simgate", "p1_reasonfirst", "p1_noctx"]
DISPLAY = {"p1_base": "Base (MiniLM)", "p1_bge": "BGE", "p1_pubmedbert": "PubMedBERT",
           "p1_bm25": "BM25", "p1_hybrid": "Hybrid (RRF)", "p1_chunk256": "Chunk 256",
           "p1_chunk1024": "Chunk 1024", "p1_k3": "$k{=}3$", "p1_k8": "$k{=}8$",
           "p1_rerank": "Rerank", "p1_simgate": "Sim.\\ gate",
           "p1_reasonfirst": "Reason-first", "p1_noctx": "Closed-book"}
# Short key segment used in \rv names (dots/dashes fine inside \csname).
KEY = {c: c.replace("p1_", "") for c in CONFIG_ORDER}
SCREEN_THRESHOLD = 0.5  # NLI max-entailment cutoff certifying a trap (phase2_screen.py)


# ---------------------------------------------------------------- formatting
def pct(x, dec=1):
    return f"{100 * x:.{dec}f}\\%"


def pct_bare(x, dec=1):
    return f"{100 * x:.{dec}f}"


def num(x, dec=3):
    return f"{x:.{dec}f}"


def pfmt(p):
    """IEEE-style p-value: scientific for tiny, 3 decimals otherwise."""
    if p >= 0.995:
        return "\\ensuremath{>0.99}"
    if p >= 0.001:
        return f"\\ensuremath{{{p:.3f}}}"
    m, e = f"{p:.2e}".split("e")
    return f"\\ensuremath{{{m}\\times10^{{{int(e)}}}}}"


def tex_escape(s):
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                 ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                 ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return s


# ---------------------------------------------------------------- loaders
def load_frontier():
    out = {}
    for arm, suf in ARMS.items():
        rows = json.loads((RESULTS / f"phase1_frontier{suf}.json").read_text())
        out[arm] = {m["config"]: m for m in rows}
        missing = set(CONFIG_ORDER) - set(out[arm])
        assert not missing, f"{arm}: frontier missing configs {missing}"
    return out


def load_stats():
    return {arm: json.loads((RESULTS / f"phase1_stats{suf}.json").read_text())
            for arm, suf in ARMS.items()}


def load_runs():
    """Per-config config.json + retrieval_report.json (authoritative; summary is stale)."""
    out = {}
    for c in CONFIG_ORDER:
        d = RESULTS / f"phase1_{c}"
        cfg = json.loads((d / "config.json").read_text())
        rep_p = d / "retrieval_report.json"
        rep = json.loads(rep_p.read_text()) if rep_p.exists() else {}
        out[c] = {"cfg": cfg, "rep": rep}
    return out


def load_completions(cfg, suf):
    p = RESULTS / f"phase1_{cfg}" / f"completions{suf}.jsonl"
    return [json.loads(l) for l in p.read_text().splitlines()]


def coverage_accuracy():
    """correct/n_answerable (not conditional on answering) — recomputed from raw
    completions because the frontier JSON only stores the conditional form."""
    out = {}
    for arm, suf in ARMS.items():
        out[arm] = {}
        for c in CONFIG_ORDER:
            rows = load_completions(c, suf)
            ans = [r for r in rows if r["answerable"]]
            correct = sum(1 for r in ans
                          if parse_response(r["response_text"])[0] == "answer"
                          and parse_response(r["response_text"])[1] == r["gold_label"])
            out[arm][c] = correct / len(ans)
    return out


def certified_fa(screen):
    """FA restricted to the NLI-certified trap subset, per arm/config."""
    certified = {o["qid"] for o in screen if o["max_entailment"] <= SCREEN_THRESHOLD}
    out = {}
    for arm, suf in ARMS.items():
        out[arm] = {}
        for c in CONFIG_ORDER:
            rows = [r for r in load_completions(c, suf)
                    if not r["answerable"] and r["qid"] in certified]
            answered = sum(1 for r in rows
                           if parse_response(r["response_text"])[0] == "answer")
            out[arm][c] = answered / len(rows)
    return out, certified


def gate_split():
    info = json.loads((RESULTS / "phase1_p1_simgate" / "gate_info.json").read_text())
    rep = json.loads((RESULTS / "phase1_p1_simgate" / "retrieval_report.json").read_text())
    answerable = {r["qid"]: r["answerable"] for r in rep["records"]}
    gated = info["gated_qids"]
    traps = sum(1 for q in gated if not answerable[q])
    answ = sum(1 for q in gated if answerable[q])
    return info["threshold"], traps, answ, len(gated)


# ---------------------------------------------------------------- numbers.tex
def build_numbers(front, stats, runs, covacc, certfa, certified, gate, screen):
    rv = {}

    def put(key, val):
        assert key not in rv, f"duplicate rv key {key}"
        rv[key] = val

    # design constants
    corpus = json.loads((RESULTS / "corpus_stats.json").read_text())
    put("design.corpus", f"{corpus['phase1']['corpus_passages']:,}".replace(",", "{,}"))
    put("design.chunks", f"{corpus['phase1']['chunks_512tok_16overlap']:,}".replace(",", "{,}"))
    put("design.nansw", "400")
    put("design.nunansw", "250")
    put("design.nquestions", "650")
    put("design.nconfigs", str(len(CONFIG_ORDER)))
    put("design.narms", "3")
    put("design.ncompletions", f"{len(CONFIG_ORDER) * 650 * 3:,}".replace(",", "{,}"))
    put("design.seed", "42")
    put("design.pqau", "15{,}000")
    put("design.refusal", tex_escape(REFUSAL_STRING))

    # per arm/config outcomes
    for arm in ARMS:
        for c in CONFIG_ORDER:
            m, k = front[arm][c], KEY[c]
            put(f"{arm}.{k}.fa", pct(m["false_answer_rate"]))
            put(f"{arm}.{k}.fa.raw", num(m["false_answer_rate"]))
            lo, hi = m["false_answer_rate_ci95"]
            put(f"{arm}.{k}.faci", f"[{pct_bare(lo)}, {pct_bare(hi)}]\\%")
            put(f"{arm}.{k}.frr", pct(m["false_refusal_rate"]))
            put(f"{arm}.{k}.frr.raw", num(m["false_refusal_rate"]))
            put(f"{arm}.{k}.acc", pct(m["accuracy_when_answering"]))
            put(f"{arm}.{k}.acc.raw", num(m["accuracy_when_answering"]))
            put(f"{arm}.{k}.unp", pct(m["unparseable_rate"]))
            put(f"{arm}.{k}.covacc", pct(covacc[arm][c]))
            put(f"{arm}.{k}.certfa", pct(certfa[arm][c]))

    # retrieval
    for c in CONFIG_ORDER:
        rep, cfg, k = runs[c]["rep"], runs[c]["cfg"], KEY[c]
        if rep.get("recall_at_k") is not None:
            put(f"recall.{k}", num(rep["recall_at_k"]))
            put(f"leaks.{k}", str(rep["holdout_leaks"]))
        put(f"k.{k}", str(cfg["top_k"]))

    # paired tests
    for arm in ARMS:
        for e in stats[arm]["mcnemar"]:
            a, b = e["pair"].split(" vs ")
            base = f"{arm}.{KEY[a]}-vs-{KEY[b]}"
            put(f"p.{base}", pfmt(e["mcnemar_p"]))
            if "n01" in e:
                assert e["n01"] + e["n10"] == e["discordant"], e["pair"]
                put(f"nzeroone.{base}", str(e["n01"]))
                put(f"nonezero.{base}", str(e["n10"]))
            put(f"disc.{base}", str(e["discordant"]))
        sp = stats[arm]["spearman_recall_fa"]
        put(f"rho.{arm}", num(sp["rho"], 2))
        put(f"rhop.{arm}", pfmt(sp["p"]))
        put(f"rhon.{arm}", str(sp["n"]))
        sp5 = stats[arm]["spearman_recall_fa_k5"]
        put(f"rho5.{arm}", num(sp5["rho"], 2))
        put(f"rhop5.{arm}", pfmt(sp5["p"]))
        put(f"rhon5.{arm}", str(sp5["n"]))

    # gate
    thr, traps, answ, ngated = gate
    put("gate.thr", num(thr, 3))
    put("gate.trapsblocked", str(traps))
    put("gate.answblocked", str(answ))
    put("gate.ngated", str(ngated))
    for arm in ARMS:
        d_fa = front[arm]["p1_base"]["false_answer_rate"] - front[arm]["p1_simgate"]["false_answer_rate"]
        d_frr = front[arm]["p1_simgate"]["false_refusal_rate"] - front[arm]["p1_base"]["false_refusal_rate"]
        put(f"gate.netfa.{arm}", str(round(d_fa * 250)))
        put(f"gate.netfrr.{arm}", str(round(d_frr * 400)))

    # screen
    put("screen.n", "250")
    put("screen.thr", num(SCREEN_THRESHOLD, 1))
    put("screen.certified", str(len(certified)))
    for t, name in [(0.5, "05"), (0.7, "07"), (0.9, "09")]:
        put(f"screen.above{name}", str(sum(1 for o in screen if o["max_entailment"] > t)))

    # budget-confound bound (results/budget_confound.json, scripts/budget_confound_check.py)
    conf = json.loads((RESULTS / "budget_confound.json").read_text())
    put("confound.verdictthenrefusal",
        str(conf["verdict_then_refusal_anywhere"]["verdict_then_refusal"]))
    for arm in ("qwen", "llama"):
        assert conf["verdict_first_base"][arm]["unparseable"] == 0, arm
        assert conf["verdict_first_base"][arm]["parse_class_not_fixed_in_first_400_chars"] == 0, arm

    # derived ratios (claim 3: scale relocates the trade-off; never hand-type "4x")
    base_ratio = (front["qwen"]["p1_base"]["false_answer_rate"]
                  / front["terra"]["p1_base"]["false_answer_rate"])
    ratios = sorted(front["qwen"][c]["false_answer_rate"] / front["terra"][c]["false_answer_rate"]
                    for c in CONFIG_ORDER
                    if c != "p1_noctx" and front["terra"][c]["false_answer_rate"] > 0)
    median = ratios[len(ratios) // 2] if len(ratios) % 2 else (
        (ratios[len(ratios) // 2 - 1] + ratios[len(ratios) // 2]) / 2)
    put("ratio.fa.qwenterra.base", f"{base_ratio:.2f}")
    put("ratio.fa.qwenterra.median", f"{median:.2f}")

    lines = [HEADER]
    lines += [f"\\defrv{{{k}}}{{{v}}}" for k, v in sorted(rv.items())]
    return "\n".join(lines) + "\n", rv


# ---------------------------------------------------------------- tables
EMB_SHORT = {"all-MiniLM-L6-v2": "MiniLM", "bge-base-en-v1.5": "BGE",
             "pubmedbert-base-embeddings": "PubMedBERT"}


def tab_grid(runs):
    rows = []
    for c in CONFIG_ORDER:
        cfg, rep = runs[c]["cfg"], runs[c]["rep"]
        tail = cfg["embedding_model"].split("/")[-1]
        emb = EMB_SHORT.get(tail, tex_escape(tail))
        if cfg.get("no_context"):
            mode, emb = "none", "---"
        else:
            mode = cfg["retrieval"]
            if cfg.get("use_reranker"):
                mode += "{+}rr"
            if cfg.get("abstain_sim_threshold"):
                mode += "{+}gate"
        recall = num(rep["recall_at_k"]) if rep.get("recall_at_k") is not None else "---"
        if rep.get("holdout_leaks") not in (0, None):
            raise AssertionError(f"{c}: holdout_leaks = {rep['holdout_leaks']} (must be 0)")
        rows.append(f"{DISPLAY[c]} & {emb} & {mode} & "
                    f"{cfg['chunk_size_tokens']} & {cfg['top_k']} & {recall} \\\\")
    return HEADER + "\n".join([
        "\\begin{table}[!t]",
        "\\caption{Retrieval configuration grid. Recall@$k$ is measured at each",
        "configuration's own $k$ over the 400 answerable questions; the automated",
        "leak check finds zero held-out gold passages in any retrieved context, in",
        "every configuration. All configurations use the verdict-first prompt except",
        "reason-first; the closed-book control receives no context",
        "(parametric-leakage probe). rr = cross-encoder reranking.}",
        "\\label{tab:grid}",
        "\\centering\\footnotesize\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{lllrrr}",
        "\\toprule",
        "Config & Embed. & Retrieval & Chunk & $k$ & Recall@$k$ \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]) + "\n"


def tab_frontier(front, runs):
    rows = []
    for c in CONFIG_ORDER:
        rep = runs[c]["rep"]
        recall = num(rep["recall_at_k"]) if rep.get("recall_at_k") is not None else "---"
        cells = [DISPLAY[c], recall]
        for arm in ARMS:
            m = front[arm][c]
            lo, hi = m["false_answer_rate_ci95"]
            cells += [pct_bare(m["accuracy_when_answering"]),
                      pct_bare(m["false_refusal_rate"]),
                      f"{pct_bare(m['false_answer_rate'])} [{pct_bare(lo)}, {pct_bare(hi)}]"]
        rows.append(" & ".join(cells) + " \\\\")
    arm_heads = " & ".join(
        f"\\multicolumn{{3}}{{c}}{{{ARM_LABEL[a]}}}" for a in ARMS)
    sub = " & ".join(["Acc & FRR & FA [95\\% CI]"] * 3)
    return HEADER + "\n".join([
        "\\begin{table*}[!t]",
        "\\caption{The three-arm safe-failure frontier. All values are percentages;",
        "$n{=}400$ answerable and $n{=}250$ unanswerable questions per configuration.",
        "Acc = accuracy conditional on answering (selection effect: arms that refuse",
        "more answer a smaller, easier subset); FRR = false-refusal rate on answerable",
        "questions; FA = false-answer rate on unanswerable questions (lower is safer),",
        "with percentile-bootstrap 95\\% CIs (10{,}000 resamples, seed 42).}",
        "\\label{tab:frontier}",
        "\\centering\\footnotesize\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{lr" + "rrl" * 3 + "}",
        "\\toprule",
        f" & & {arm_heads} \\\\",
        "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}\\cmidrule(lr){9-11}",
        f"Config & Recall@$k$ & {sub} \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table*}",
    ]) + "\n"


def tab_mcnemar(stats):
    pair_order = [e["pair"] for e in stats["qwen"]["mcnemar"]]
    by_arm = {arm: {e["pair"]: e for e in stats[arm]["mcnemar"]} for arm in ARMS}
    rows = []
    for pair in pair_order:
        a, b = pair.split(" vs ")
        cells = [f"{DISPLAY[a]} vs.\\ {DISPLAY[b]}"]
        for arm in ARMS:
            e = by_arm[arm][pair]
            cells.append(f"{e.get('n10', '?')}/{e.get('n01', '?')}")
            cells.append(pfmt(e["mcnemar_p"]))
        rows.append(" & ".join(cells) + " \\\\")
    arm_heads = " & ".join(f"\\multicolumn{{2}}{{c}}{{{ARM_LABEL[a]}}}" for a in ARMS)
    return HEADER + "\n".join([
        "\\begin{table*}[!t]",
        "\\caption{Paired McNemar exact tests on false-answer outcomes over the same",
        "250 unanswerable questions. $n_{10}/n_{01}$ = questions the first config",
        "answers but the second refuses / vice versa; $p$ from an exact binomial test",
        "on the discordant pairs.}",
        "\\label{tab:mcnemar}",
        "\\centering\\footnotesize\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{l" + "cl" * 3 + "}",
        "\\toprule",
        f" & {arm_heads} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
        "Pair & $n_{10}/n_{01}$ & $p$ & $n_{10}/n_{01}$ & $p$ & $n_{10}/n_{01}$ & $p$ \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table*}",
    ]) + "\n"


def tab_gate(front, stats, gate):
    thr, traps, answ, _ = gate
    rows = []
    for arm in ARMS:
        base, sg = front[arm]["p1_base"], front[arm]["p1_simgate"]
        e = next(x for x in stats[arm]["mcnemar"] if x["pair"] == "p1_base vs p1_simgate")
        rows.append(" & ".join([
            ARM_LABEL[arm],
            pct_bare(base["false_answer_rate"]), pct_bare(sg["false_answer_rate"]),
            str(round((base["false_answer_rate"] - sg["false_answer_rate"]) * 250)),
            pct_bare(base["false_refusal_rate"]), pct_bare(sg["false_refusal_rate"]),
            str(round((sg["false_refusal_rate"] - base["false_refusal_rate"]) * 400)),
            pfmt(e["mcnemar_p"]),
        ]) + " \\\\")
    return HEADER + "\n".join([
        "\\begin{table}[!t]",
        "\\caption{Similarity-gate decomposition. The gate (top-1 score",
        f"$<{num(thr, 3)}$, the 5th percentile of answerable-question top-1 scores)",
        f"mechanically blocks {traps}/250 unanswerable and {answ}/400 answerable",
        "questions before generation. Outcome-level effects are smaller: within each",
        "block, the final column counts questions whose outcome changed vs.\\ base",
        "(FA block: false answers converted to refusals; FRR block: answerable",
        "questions newly refused).}",
        "\\label{tab:gate}",
        "\\centering\\footnotesize\\setlength{\\tabcolsep}{3pt}",
        "\\begin{tabular}{lrrrrrrl}",
        "\\toprule",
        " & \\multicolumn{3}{c}{FA (\\%)} & \\multicolumn{3}{c}{FRR (\\%)} & \\\\",
        "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
        "Family & base & gate & $\\Delta n$ & base & gate & $\\Delta n$ & $p$ \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]) + "\n"


def tab_screen(front, certfa, screen, certified):
    key_configs = ["p1_base", "p1_bge", "p1_bm25", "p1_reasonfirst"]
    rows = []
    for c in key_configs:
        cells = [DISPLAY[c]]
        for arm in ARMS:
            cells += [pct_bare(front[arm][c]["false_answer_rate"]),
                      pct_bare(certfa[arm][c])]
        rows.append(" & ".join(cells) + " \\\\")
    above = {t: sum(1 for o in screen if o["max_entailment"] > t) for t in (0.5, 0.7, 0.9)}
    arm_heads = " & ".join(f"\\multicolumn{{2}}{{c}}{{{ARM_LABEL[a]}}}" for a in ARMS)
    return HEADER + "\n".join([
        "\\begin{table}[!t]",
        "\\caption{False-answer rates on all 250 held-out questions vs.\\ the",
        f"{len(certified)} NLI-certified traps (max entailment $\\le{SCREEN_THRESHOLD}$",
        "against every retrieved passage). Certification excludes"
        f" {above[0.5]} questions with related corpus evidence (the count is identical",
        f"at a 0.7 threshold; {above[0.9]} exceed 0.9). Headline rates are essentially",
        "unchanged: false answers track topical similarity, not evidential support.}",
        "\\label{tab:screen}",
        "\\centering\\footnotesize\\setlength{\\tabcolsep}{3.5pt}",
        "\\begin{tabular}{l" + "rr" * 3 + "}",
        "\\toprule",
        f" & {arm_heads} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
        "Config & all & cert. & all & cert. & all & cert. \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]) + "\n"


def tab_prompts():
    import prompts as P
    blocks = []
    for title, text in [("System prompt v2 (verdict-first; all configs except reason-first)",
                         P.GENERATOR_SYSTEM_V2),
                        ("System prompt v1-hardened (reason-first config only)",
                         P.GENERATOR_SYSTEM_V1_HARDENED),
                        ("User template", P.GENERATOR_USER_TEMPLATE)]:
        body = tex_escape(text.strip()).replace("\n", "\\par\n")
        blocks += [f"\\noindent\\textbf{{{tex_escape(title)}}}\\par\\smallskip",
                   "\\begin{quote}\\ttfamily\\footnotesize\\raggedright",
                   body,
                   "\\end{quote}\\bigskip", ""]
    return HEADER + "\n".join(blocks)


# ---------------------------------------------------------------- check mode
def check(numbers_txt):
    ok = True
    defined = set(re.findall(r"\\defrv\{([^}]+)\}", numbers_txt))
    sections = sorted((PAPER / "sections").glob("*.tex")) if (PAPER / "sections").exists() else []
    used = set()
    for f in sections:
        text = "\n".join(l for l in f.read_text().splitlines()
                         if not l.lstrip().startswith("%"))
        for key in re.findall(r"\\rv\{([^}]+)\}", text):
            used.add(key)
            if key not in defined:
                print(f"FAIL {f.name}: \\rv{{{key}}} not defined in numbers.tex")
                ok = False
        # bare result-like literals in prose (0.xxx proportions or xx.x% values)
        for pat in (r"(?<![\d.])0\.\d{2,}", r"\d+\.\d+\\%"):
            for m in re.findall(pat, text):
                print(f"FAIL {f.name}: bare numeric literal '{m}' — use an \\rv macro")
                ok = False
    unused = defined - used
    if sections and unused:
        print(f"note: {len(unused)} rv keys defined but not yet used (fine at skeleton stage)")
    return ok


# ---------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    front, stats, runs = load_frontier(), load_stats(), load_runs()
    screen = json.loads((RESULTS / "phase2_screen.json").read_text())
    covacc = coverage_accuracy()
    certfa, certified = certified_fa(screen)
    gate = gate_split()

    art = json.loads((ROOT / "artifact" / "unanswerable_medical_qa_v1.json").read_text())
    assert len(certified) == art["metadata"]["n_certified"], \
        f"screen certification ({len(certified)}) != artifact metadata ({art['metadata']['n_certified']})"
    assert gate[1] == 114 and gate[2] == 20, f"gate split changed: {gate[1]}/{gate[2]}"

    numbers_txt, rv = build_numbers(front, stats, runs, covacc, certfa, certified,
                                    gate, screen)
    outputs = {
        PAPER / "numbers.tex": numbers_txt,
        TABLES / "tab_grid.tex": tab_grid(runs),
        TABLES / "tab_frontier.tex": tab_frontier(front, runs),
        TABLES / "tab_mcnemar.tex": tab_mcnemar(stats),
        TABLES / "tab_gate.tex": tab_gate(front, stats, gate),
        TABLES / "tab_screen.tex": tab_screen(front, certfa, screen, certified),
        TABLES / "tab_prompts.tex": tab_prompts(),
    }

    if args.check:
        ok = True
        for path, content in outputs.items():
            if not path.exists():
                print(f"FAIL missing {path.relative_to(ROOT)}")
                ok = False
            elif path.read_text() != content:
                print(f"FAIL drift: {path.relative_to(ROOT)} differs from regenerated content")
                ok = False
        ok = check(numbers_txt) and ok
        print("check:", "OK" if ok else "FAILED")
        sys.exit(0 if ok else 1)

    TABLES.mkdir(parents=True, exist_ok=True)
    for path, content in outputs.items():
        path.write_text(content)
        print("wrote", path.relative_to(ROOT))
    print(f"{len(rv)} \\rv keys defined")


if __name__ == "__main__":
    main()
